from datetime import datetime
from typing import Any
from sqlalchemy import Column, Integer, String, Float, DateTime, Text, JSON
from database import Base


class InsuranceProduct(Base):
    """Catalog of available micro-insurance products."""
    __tablename__ = "insurance_products"

    id = Column(Integer, primary_key=True, index=True)
    category = Column(String, index=True)           # e.g. "device_protection"
    name = Column(String)
    description = Column(Text)
    base_price = Column(Float)                      # Fixed base premium in SGD
    coverage_amount = Column(Float)                 # Max payout in SGD
    rate_pct = Column(Float)                        # % of deal value added to premium
    risk_tier = Column(String, default="medium")    # low / medium / high


class Recommendation(Base):
    """Each recommendation generated by the pipeline for a user deal."""
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, index=True)
    deal_snapshot = Column(JSON)                    # Full deal dict at time of rec
    intent = Column(String)
    confidence = Column(Float)
    product_id = Column(Integer)
    product_name = Column(String)
    premium = Column(Float)
    variant = Column(String)                        # A/B variant assigned
    copy_headline = Column(String)
    copy_cta = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)


class ABVariant(Base):
    """A/B variant definitions (seeded: A = control, B = experiment)."""
    __tablename__ = "ab_variants"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True)              # "A" or "B"
    description = Column(String)


class Event(Base):
    """Tracks every user interaction with an insurance offer."""
    __tablename__ = "events"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, index=True)
    recommendation_id = Column(Integer, index=True)
    event_type = Column(String)                     # impression/click/accept/decline
    variant = Column(String)
    category = Column(String)
    premium = Column(Float, nullable=True)          # Only set on accept events
    created_at = Column(DateTime, default=datetime.utcnow)
